apiVersion: v1
kind: Secret
metadata:
  name: sqlpassword
  namespace: beta
stringData:
  password: "EjHl/fLxkZdASQ=="
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    azure.workload.identity/use: "true"
    run: api
  name: api
  namespace: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      serviceAccountName: richeneyaks-beta
      containers:
      - image: erjosito/yadaapi:1.0
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SQL_SERVER_USERNAME
          value: "azure"
        - name: SQL_SERVER_FQDN
          value: "richeneyaks-beta-sql.database.windows.net"
        - name: SQL_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: password
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: beta
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: api