apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: richeneyaks-beta-secrets
  namespace: beta
  labels:
    customer: beta
spec:
  provider: azure
  secretObjects:
    - secretName: richeneyaks-beta-secrets-sql
      labels:
        customer: beta
      data:
        - key: dbname
          objectName: sql-dbname
        - key: username
          objectName: sql-username
        - key: password
          objectName: sql-password
      type: Opaque
  parameters:
    tenantId: 3c584bbd-915f-4c70-9f2e-7217983f22f6
    clientID: cf37a6f2-8e00-494e-831f-59b1823f82da
    keyvaultName: richeneyaks-beta-kv
    objects:  |
      array:
        - |
          objectName: sql-fqdn
          objectType: secret
        - |
          objectName: sql-server
          objectType: secret
        - |
          objectName: sql-dbname
          objectType: secret
        - |
          objectName: sql-username
          objectType: secret
        - |
          objectName: sql-password
          objectType: secret
    usePodIdentity: "false"
    useVMManagedIdentity: "false"