apiVersion: v1
kind: Pod
metadata:
  name: msal-go
  namespace: alpha
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: richeneyaks-alpha
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: https://richeneyaks-alpha-kv.vault.azure.net/
      - name: SECRET_NAME
        value: my-secret
  nodeSelector:
    kubernetes.io/os: linux
