apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
  namespace: alpha
spec:
  provider: azure
  parameters:
    tenantId: 3c584bbd-915f-4c70-9f2e-7217983f22f6
    clientID: 084c4704-c714-4ffb-9d2b-298060584ece
    keyvaultName: richeneyaks-alpha-kv
    objects:  |
      array:
        - |
          objectName: car
          objectType: secret
        - |
          objectName: city
          objectType: secret
        - |
          objectName: food
          objectType: secret
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
