apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
  namespace: alpha
  labels:
    customer: alpha
spec:
  provider: azure
  secretObjects:
    - secretName: websecrets
      labels:
        customer: alpha
        container: web
      data:
        - key: my-food
          objectName: food
      type: Opaque
    - secretName: apisecrets
      labels:
        customer: alpha
        container: api
      data:
        - key: my-car
          objectName: car
        - key: my-city
          objectName: city
      type: Opaque
  parameters:
    tenantId: 3c584bbd-915f-4c70-9f2e-7217983f22f6
    clientID: 084c4704-c714-4ffb-9d2b-298060584ece
    keyvaultName: richeneyaks-alpha-kv
    objects: |
      array:
        - |
          objectName: car
          objectType: secret
        - |
          objectName: city
          objectType: secret
        - |
          objectName: food
          objectType: secret
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
